### ISSUE TITLE
Cannot download apk on Filefox

### ISSUE THREAD

**Issue by surattum** [allangoing/apkshellext#53]
I download apk file on Firefox
Cannot download to finish
And cannot delete apk file, because file in use 

<a href="http://picture.in.th/id/247a6bfb87ad158b1ee8a074fe4fc65c"  target="_blank"><img border="0" src="http://image.free.in.th/v/2013/ib/160503051653.png" alt="images by free.in.th" /></a>

Note:test on Windows 8.1, 10

**Comment by sylveon** [comment]
This issue concerns Firefox, not apkshellext.
If you want to delete the file, simply cancel the download.
Apk not downloading is probably more related to the website you used

**Comment by surattum** [comment]
The issue caused by apkshellext.
I cancel the download, But cannot delete apk file (show file in use)
Solve uninstall apkshellext. can delete apk

**Comment by kkguo** [comment]
Hi, Surattum
Thx for feedback, it maybe caused by a unhandled handler leak. Can you plz
help me to debug this issue?
Can you repeat the problem?
If you still see the file cannot be deleted, plz restart explorer, and try
delete again.
Can you send me the broken apk file?

**Comment by surattum** [comment]
I restart explorer and try delete again, But still cannot delete
All apk files that are downloaded on Firefox, Will cannot load complete
Because the file is locked from being apkshellext used.

**Comment by kkguo** [comment]
You suppose to see an green android icon for a broken apk file.
But anyway, can you send me a broken apk file? You can paste it here. I cannot repeat the error you have.

**Comment by kkguo** [comment]
@surattum btw, I didn't noticed you have a snapshot as it is blocked by my VPN, and I guess the link is expired now, can you just paste it here?

**Comment by surattum** [comment]
Download apk file on Firefox
Firefox create 2 file name.apk and name.apk.part
download completed cannot integration file name.apk.part become name.apk
I cancel the download. Incomplete apk files and file in use, I can not delete it.
![apk](https://cloud.githubusercontent.com/assets/13364144/15062002/ef9c0b44-1365-11e6-8176-305ac8f81935.png)

**Comment by kkguo** [comment]
@surattum , I installed a firefox, and tried download an apk file, but I didn't see your problem.
I understand you cannot delete that apk file, but I think you can still copy it. Can you paste the apk file here? I need to check the apk internally to find what is locking the file.

**Comment by ggets** [comment]
i have the same problem and it has nothing to do with firefox. the shell extension locks the empty file with the apk extension trying to read it and it can't be filled with any data afterwards because it is locked. restarting explorer also doesn't fix the issue if the file is on the desktop because after you restart the shell extension tries to read the empty file again (probably to generate the icon?!) so the issue concerns every program creating an empty apk in an opened folder in explorer or other program using the shell extension and trying to write data to it after that. This is not a problem microsoft or mozilla have to fix. it's not the proper behaviour for the extension to lock a file until it can read it successfully.

**Comment by kkguo** [comment]
I didn't see issue in chrome, as it create empty apk as well.
I'm not a firefox user, but if it's still an issue, please reopen this.
