### ISSUE TITLE
apkshellext corrupts FileTypes Manager

### ISSUE THREAD

**Issue by MarkoIndaco** [allangoing/apkshellext#69]
Hi, What happens is I try FileTypes Manager (Nirsoft) but I wasn't able to change the .apk icons so, checking on the Net i found apkshellext so I would give a try, but because also this don't works on my pc for some reason, I retry FileTypes Manager (Nirsoft) and I notice that, after apllicating the apkshellext command, the FileTypes Manager gives an error. **I understand that this is mainly their (Nirsoft) problem (I have already written to them)**, but I write you to inform (and to ask) if a possible reason for that apkshellext didn't works for me it's because I run and try FTM before?... maybe some conflict...
EDIT:
I confirm that, after uninstalling the apkshellext, FileTypes Manager load fine again.
Maybe you can put some warning about this issue.
Hope can help.

Greetings

**Comment by kkguo** [comment]
Hi, Marko

Thanks for the info, apkshellext is a dll registered in your registry, but
because it's based on .net, it may conflict with native MFC shell extension
programs. You maybe try uninstall apkshellext first and restart your
computer (not necessary but recommended), I think I clean everything in the
uninstall routine..

BR,
KK

Marko <notifications@github.com>于2017年10月6日周五 下午5:55写道：

**Comment by MarkoIndaco** [comment]
Oh that's nice. Thank you for reply. Keep up the good work!

**Comment by Rocker2234** [comment]
Until a fix is released you can just disable loading of icons in file types manager and everything will be normal!

**Comment by killerjn** [comment]
I had the same problem but with m4a files
![2018-11-18 20_26_47-musica](https://user-images.githubusercontent.com/32747059/48681465-8ed52d00-eb70-11e8-9beb-46caa238c896.jpg)

I had to reinstall the video codecs

**Comment by kkguo** [comment]
close this now, reopen if problem persists
